export const colors = {
  surface: '#15121b',
  surfaceDim: '#15121b',
  surfaceBright: '#3c3742',
  surfaceContainerLowest: '#100d16',
  surfaceContainerLow: '#1d1a24',
  surfaceContainer: '#221e28',
  surfaceContainerHigh: '#2c2833',
  surfaceContainerHighest: '#37333e',
  surfaceTint: '#d2bbff',
  surfaceVariant: '#37333e',
  onSurface: '#e8dfee',
  onSurfaceVariant: '#ccc3d8',
  onBackground: '#e8dfee',
  inverseSurface: '#e8dfee',
  inverseOnSurface: '#15121b',
  outline: '#958da1',
  outlineVariant: '#4a4455',
  primary: '#d2bbff',
  onPrimary: '#3f008e',
  primaryContainer: '#7c3aed',
  onPrimaryContainer: '#ede0ff',
  inversePrimary: '#732ee4',
  primaryFixed: '#eaddff',
  primaryFixedDim: '#d2bbff',
  onPrimaryFixed: '#25005a',
  onPrimaryFixedVariant: '#5a00c6',
  secondary: '#ccbeff',
  onSecondary: '#332664',
  secondaryContainer: '#4a3d7c',
  onSecondaryContainer: '#baabf3',
  secondaryFixed: '#e7deff',
  secondaryFixedDim: '#ccbeff',
  onSecondaryFixed: '#1e0e4e',
  onSecondaryFixedVariant: '#4a3d7c',
  tertiary: '#ffb784',
  onTertiary: '#4f2500',
  tertiaryContainer: '#a15100',
  onTertiaryContainer: '#ffe0cd',
  tertiaryFixed: '#ffdcc6',
  tertiaryFixedDim: '#ffb784',
  onTertiaryFixed: '#301400',
  onTertiaryFixedVariant: '#713700',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdad6',
  background: '#15121b',
  success: '#4ade80',
  successContainer: 'rgba(74, 222, 128, 0.1)',
} as const;

export const navigationTheme = {
  dark: true,
  colors: {
    primary: colors.primary,
    background: colors.background,
    card: colors.surfaceContainer,
    text: colors.onSurface,
    border: colors.outlineVariant,
    notification: colors.error,
  },
  fonts: {
    regular: {
      fontFamily: 'System',
      fontWeight: '400' as const,
    },
    medium: {
      fontFamily: 'System',
      fontWeight: '500' as const,
    },
    bold: {
      fontFamily: 'System',
      fontWeight: '700' as const,
    },
    heavy: {
      fontFamily: 'System',
      fontWeight: '800' as const,
    },
  },
};
