-- Migration 0034: Daily AI reports (evening 9:30 PM report + morning 8:30 AM briefing)
-- Generated by the ai-daily-report edge function (Groq), pushed via Expo Push.
-- Mobile fetches the latest report for a date via RLS-protected select.

CREATE TABLE IF NOT EXISTS daily_reports (
    id          TEXT PRIMARY KEY DEFAULT (gen_random_uuid())::TEXT,
    user_id     TEXT NOT NULL,
    report_date TEXT NOT NULL,               -- YYYY-MM-DD (IST)
    mode        TEXT NOT NULL DEFAULT 'evening',  -- 'evening' | 'morning'
    content     JSONB NOT NULL DEFAULT '{}'::jsonb,  -- {summary, sections[], disclaimer}
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_daily_reports_user_date_mode ON daily_reports(user_id, report_date, mode);
CREATE INDEX IF NOT EXISTS idx_daily_reports_user_date ON daily_reports(user_id, report_date);

ALTER TABLE daily_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "User owns daily_reports" ON daily_reports FOR ALL USING (user_id = auth.uid()::text);

-- Realtime for web app parity
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'daily_reports'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.daily_reports;
    END IF;
END $$;

-- pg_cron: evening report 9:30 PM IST = 16:00 UTC, morning briefing 8:30 AM IST = 03:00 UTC
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

DO $$
BEGIN
  PERFORM cron.unschedule('ai-daily-report-evening');
EXCEPTION
  WHEN OTHERS THEN NULL;
END $$;

DO $$
BEGIN
  PERFORM cron.unschedule('ai-daily-report-morning');
EXCEPTION
  WHEN OTHERS THEN NULL;
END $$;

SELECT cron.schedule(
  'ai-daily-report-evening',
  '30 16 * * *',
  $$
  SELECT net.http_post(
    url := 'https://rkmouoglorsnijmemmcd.supabase.co/functions/v1/ai-daily-report',
    body := '{"mode":"evening"}'::jsonb,
    headers := '{"Content-Type": "application/json"}'::jsonb
  );
  $$
);

SELECT cron.schedule(
  'ai-daily-report-morning',
  '0 3 * * *',
  $$
  SELECT net.http_post(
    url := 'https://rkmouoglorsnijmemmcd.supabase.co/functions/v1/ai-daily-report',
    body := '{"mode":"morning"}'::jsonb,
    headers := '{"Content-Type": "application/json"}'::jsonb
  );
  $$
);
